### ISSUE TITLE
Removing hash from urls

### ISSUE THREAD

**Issue by NetOpWibby** [composi/router#1]
Is this possible? I'd much rather have URLs without `#` in them.

**Comment by rbiggs** [comment]
Try using [Universal Router](https://www.npmjs.com/package/universal-router). That's an isomorphic router. Has the same interface as @composi/router (inspired me). @composi/router just does hashes because it's only for front end. Universal Router i's a lot bigger, but it does work just fine.

**Comment by NetOpWibby** [comment]
Ah okay, I’ll try that!

**Comment by rbiggs** [comment]
Like I said, it has the same api:
```javascript
{
    path: "/",
    action: () => {
      // Do something when main page loads
   }
}
```
For me, problem with non-hash solutions is that if you reload the browser during development, it can process the url change usually. Whereas hashes work flawlessly. I'v tried every router out there and have always had problems with page reloads :-/ I dunno, maybe I'm just jinked with routes.
